FROM python:3.10-slim

WORKDIR /dashboard

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY dashboard.py .


CMD ["sh", "-c", "streamlit run dashboard.py --server.address 0.0.0.0 --server.port $PORT"]




